runtime: pyton38

instance_class: F1

env_variables:
  MYSQL_USER: 'root'
  MYSQL_PASSWORD: 'Abdu_formed_team0'
  MYSQL_DB: 'AbDB'
  MYSQL_HOST: '34.68.50.19'

handlers:
  url: /img
  static_dir: static/img

  url: /script
  static_dir: static/script

  url: /styles
  static_dir: static/styles
